Update gha-stage.yml

diff --git a/.github/workflows/gha-stage.yml b/.github/workflows/gha-stage.yml
--- a/.github/workflows/gha-stage.yml
+++ b/.github/workflows/gha-stage.yml
@@ -26,8 +26,8 @@ jobs:
         run: echo "Hello, world! Workflow is running."
 
       # 🚨 Simulate failure: uncomment to test issue creation on failure
-      - name: Simulate failure
-        run: exit 1
+     # - name: Simulate failure
+      #  run: exit 1
 
       - name: Slack notification on failure or cancellation
         if: failure() || cancelled()
